"""
Vault & Shares workflows — thin Temporal shells.
Business logic lives in services/vault_service.py.

Task queue: vault-queue

Workflows:
  ShareExpiryWorkflow     — expire a share token at its scheduled time (durable timer)
  ShareRevocationWorkflow — immediately revoke a share token (user-initiated)
  DocumentShareWorkflow   — create a share token with OTP verification flow
"""
from datetime import datetime, timedelta, timezone

from temporalio import workflow, activity
from temporalio.common import RetryPolicy

_RETRY = RetryPolicy(
    maximum_attempts=3,
    initial_interval=timedelta(seconds=10),
    backoff_coefficient=2.0,
    maximum_interval=timedelta(minutes=5),
)


# ── Activities (implementations in services/share_service.py) ─────────────────

@activity.defn(name="expire_share_token")
async def expire_share_token(params: dict) -> None:
    import asyncpg

    from config import get_settings
    from services.share_service import ShareService

    settings = get_settings()
    db = await asyncpg.connect(settings.db_dsn)
    try:
        await ShareService(db=db, redis=None, settings=settings).mark_expired(params["share_id"])
    finally:
        await db.close()

@activity.defn(name="revoke_share_token")
async def revoke_share_token(params: dict) -> None:
    import asyncpg

    from config import get_settings
    from services.share_service import ShareService

    settings = get_settings()
    db = await asyncpg.connect(settings.db_dsn)
    try:
        await ShareService(db=db, redis=None, settings=settings).revoke_by_id(params["share_id"])
    finally:
        await db.close()

@activity.defn(name="create_share_token")
async def create_share_token(params: dict) -> dict:
    import asyncpg

    from config import get_settings
    from services.share_service import ShareService

    settings = get_settings()
    db = await asyncpg.connect(settings.db_dsn)
    try:
        return await ShareService(db=db, redis=None, settings=settings).create(
            employee_user_id=params["employee_user_id"],
            document_ids=params["document_ids"],
            expires_hours=params.get("expires_hours", 72),
            max_views=params.get("max_views", 3),
            recipient_label=params.get("recipient_label"),
            otp_required=params.get("otp_required", False),
            recipient_email=params.get("recipient_email"),
        )
    finally:
        await db.close()

@activity.defn(name="send_share_otp")
async def send_share_otp(params: dict) -> None:
    """Delivers the OTP generated by create_share_token to the recipient's mobile.
    A Temporal activity (unlike an HTTP handler) is the right place for this —
    it gets retry/backoff/timeout for free, matching the "durable delivery"
    intent already used by WebhookDeliveryWorkflow/NotificationDeliveryWorkflow."""
    import asyncpg
    import redis.asyncio as redis_async

    from config import get_settings
    from services.circuit_breaker import CircuitBreaker
    from services.config_service import ConfigService
    from services.sms_service import SMSService

    mobile = params.get("recipient_mobile")
    otp = params.get("otp")
    if not mobile or not otp:
        return

    settings = get_settings()
    db = await asyncpg.connect(settings.db_dsn)
    rdb = redis_async.from_url(settings.redis_url)
    try:
        config = ConfigService(db, rdb)
        breaker = CircuitBreaker(rdb, config)
        await SMSService(settings, config, breaker).send_otp(
            mobile, otp, tenant_id=params.get("tenant_id"),
        )
    finally:
        await db.close()
        await rdb.aclose()

@activity.defn(name="notify_share_accessed")
async def notify_share_accessed(params: dict) -> None:
    """Notifies the document owner (employee) their share was accessed —
    routed through NotifConsumer's existing SHARE_ACCESSED template."""
    from kafka.producer import get_kafka_producer

    kafka = await get_kafka_producer()
    await kafka.publish(
        "prana.notifications",
        {
            "event_type": "SHARE_ACCESSED",
            "employee_user_id": params["employee_user_id"],
            "tenant_id": params.get("tenant_id"),
        },
        key=params["employee_user_id"],
    )

@activity.defn(name="get_share_config")
async def get_share_config(params: dict) -> str:
    import asyncpg
    import redis.asyncio as redis_async

    from config import get_settings
    from services.config_service import ConfigService

    settings = get_settings()
    db = await asyncpg.connect(settings.db_dsn)
    rdb = redis_async.from_url(settings.redis_url)
    try:
        value = await ConfigService(db, rdb).get(params["key"], params.get("tenant_id"))
        return value if value is not None else params.get("default", "")
    finally:
        await db.close()
        await rdb.aclose()


# ── ShareExpiryWorkflow (Pattern 1 — Durable Timer) ──────────────────────────

@workflow.defn(name="ShareExpiryWorkflow")
class ShareExpiryWorkflow:
    """
    Schedules expiry of a share token at its `expires_at` timestamp.
    Started when a share is created (POST /vault/shares).
    When the timer fires: marks share_token as expired in DB + invalidates Redis cache entry.
    """

    @workflow.run
    async def run(self, params: dict) -> None:
        expires_at   = datetime.fromisoformat(params["expires_at"]).replace(tzinfo=timezone.utc)
        wait_seconds = max(0, (expires_at - workflow.now()).total_seconds())
        if wait_seconds > 0:
            await workflow.sleep(timedelta(seconds=wait_seconds))
        await workflow.execute_activity(
            expire_share_token, params,
            start_to_close_timeout=timedelta(minutes=5),
            retry_policy=_RETRY,
        )


# ── ShareRevocationWorkflow (Pattern 1 — fast, immediate) ────────────────────

@workflow.defn(name="ShareRevocationWorkflow")
class ShareRevocationWorkflow:
    """
    Employee revokes a share link (DELETE /vault/shares/{token_id}).
    Immediately invalidates the token in DB + Redis cache.
    Thin wrapper so revocation appears in Temporal audit trail.
    """

    @workflow.run
    async def run(self, params: dict) -> None:
        await workflow.execute_activity(
            revoke_share_token, params,
            start_to_close_timeout=timedelta(minutes=5),
            retry_policy=_RETRY,
        )


# ── DocumentShareWorkflow (Pattern 2 — Signal-Driven, with OTP) ──────────────

@workflow.defn(name="DocumentShareWorkflow")
class DocumentShareWorkflow:
    """
    Creates a share token and sends an OTP to the recipient's mobile.
    Waits for OTP verification via 'otp_verified' signal.
    If no signal within share_otp_ttl_minutes (default: 10): token auto-expires.
    Once verified: notifies the document owner that their share was accessed.
    """

    def __init__(self):
        self._otp_verified = False
        self._accessor_id: str = ""

    @workflow.signal(name="otp_verified")
    def otp_verified(self, payload: dict) -> None:
        self._otp_verified = True
        self._accessor_id = payload.get("accessor_id", "")

    @workflow.run
    async def run(self, params: dict) -> dict:
        ttl_str = await workflow.execute_activity(
            get_share_config,
            {"key": "share_otp_ttl_minutes", "tenant_id": params.get("tenant_id"), "default": "10"},
            start_to_close_timeout=timedelta(minutes=2),
        )
        return await self._execute(params, ttl_str)

    async def _execute(self, params: dict, ttl_str: str) -> dict:
        token_data = await workflow.execute_activity(
            create_share_token, params,
            start_to_close_timeout=timedelta(minutes=5), retry_policy=_RETRY,
        )
        await workflow.execute_activity(
            send_share_otp, {**params, **token_data},
            start_to_close_timeout=timedelta(minutes=5), retry_policy=_RETRY,
        )
        verified = await workflow.wait_condition(
            lambda: self._otp_verified,
            timeout=timedelta(minutes=int(ttl_str)),
        )
        if verified and self._otp_verified:
            await workflow.execute_activity(
                notify_share_accessed,
                {**params, **token_data, "accessor_id": self._accessor_id},
                start_to_close_timeout=timedelta(minutes=5), retry_policy=_RETRY,
            )
        else:
            await workflow.execute_activity(
                expire_share_token, token_data,
                start_to_close_timeout=timedelta(minutes=5), retry_policy=_RETRY,
            )
        return token_data
